version: '3.7'

services:
  app:
    runtime: nvidia
    container_name: questgen
    environment:
      - PYTHONUNBUFFERED=1
      - NVIDIA_VISIBLE_DEVICES=all
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - backend
networks:
  backend:
